[global]
[[global.environment]]
name = 'qwe'
value = 'asd'

[hasura]
version = 'v2.27.0-ce'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = 'HS256'
key = '{{ secrets.HASURA_GRAPHQL_JWT_SECRET }}'

[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']

[hasura.logs]
level = 'warn'

[hasura.events]
httpPoolSize = 100

[functions]
[functions.node]
version = 16

[auth]
version = '0.19.1'

[auth.redirections]
clientUrl = 'http://localhost:3000'

[auth.signUp]
enabled = true

[auth.user]
[auth.user.roles]
default = 'user'
allowed = ['user', 'me']

[auth.user.locale]
default = 'en'
allowed = ['en']

[auth.user.gravatar]
enabled = true
default = 'blank'
rating = 'g'

[auth.user.email]

[auth.user.emailDomains]

[auth.session]
[auth.session.accessToken]
expiresIn = 900

[auth.session.refreshToken]
expiresIn = 43200

[auth.method]
[auth.method.anonymous]
enabled = false

[auth.method.emailPasswordless]
enabled = false

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = true
passwordMinLength = 9

[auth.method.smsPasswordless]
enabled = false

[auth.method.oauth]
[auth.method.oauth.apple]
enabled = false

[auth.method.oauth.azuread]
tenant = 'common'
enabled = false

[auth.method.oauth.bitbucket]
enabled = false

[auth.method.oauth.discord]
enabled = false

[auth.method.oauth.facebook]
enabled = false

[auth.method.oauth.github]
enabled = false

[auth.method.oauth.gitlab]
enabled = false

[auth.method.oauth.google]
enabled = false

[auth.method.oauth.linkedin]
enabled = false

[auth.method.oauth.spotify]
enabled = false

[auth.method.oauth.strava]
enabled = false

[auth.method.oauth.twitch]
enabled = false

[auth.method.oauth.twitter]
enabled = false

[auth.method.oauth.windowslive]
enabled = false

[auth.method.oauth.workos]
enabled = false

[auth.method.webauthn]
enabled = false

[auth.method.webauthn.attestation]
timeout = 60000

[auth.totp]
enabled = false

[postgres]
version = '14.5-20230104-1'

[provider]

[storage]
version = '0.3.4'

[observability]
[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'

# [[services]]
# name="mysql"
# image="docker.io/mysql:8-oracle"

#     [[services.environment]]
#     name="MYSQL_DATABASE"
#     value="wordpress"

#     [[services.environment]]
#     name="MYSQL_USER"
#     value="wordpress"

#     [[services.environment]]
#     name="MYSQL_PASSWORD"
#     value="{{ secrets.MYSQL_WORDPRESS_PASSWORD }}"

#     [[services.environment]]
#     name="MYSQL_ROOT_PASSWORD"
#     value="{{ secrets.MYSQL_ROOT_PASSWORD }}"

#     [[services.ports]]
#     port=3306
#     type="tcp"

#     [services.resources]
#     replicas=1

#         [services.resources.compute]
#         cpu=250
#         memory=512

#         [[services.resources.storage]]
#         capacity=1
#         path="/var/lib/mysql"

# [[services]]
# name="hello-world"
# image="docker.io/wordpress:6.2.2-php8.2"

#     [[services.environment]]
#     name="WORDPRESS_DB_HOST"
#     value="mysql"

#     [[services.environment]]
#     name="WORDPRESS_DB_USER"
#     value="wordpress"

#     [[services.environment]]
#     name="WORDPRESS_DB_PASSWORD"
#     value="{{ secrets.MYSQL_WORDPRESS_PASSWORD }}"

#     [[services.environment]]
#     name="WORDPRESS_DB_NAME"
#     value="wordpress"

#     [[services.ports]]
#     port=80
#     type="http"
#     publish=true

#     [services.resources]
#     replicas=1

#         [services.resources.compute]
#         cpu=250
#         memory=512
